### ISSUE TITLE
Add layer opacity control to all types of layers

### ISSUE THREAD

**Issue by ComBatVision** [WorldWindEarth/WorldWindKotlin#23]
Add layer opacity control to all types of layers, especially Tiled Image layers.

Now this parameter exists in Layer interface, but it is used only for Graticule line color now.

Opacity implementation can be ported from WorldWindJS.

**Comment by GuzulFromUkraine** [comment]
Fixed by #40

**Comment by ComBatVision** [comment]
Technically opacity works, but it influence somehow next layers, which should not have opacity.
Please test if placemarks layer has pacity but then shapes layer has no opacity. It should draw opaque shapes.

**Comment by ComBatVision** [comment]
Plus this opacity feature should be compatible with imageColor.alpha opacity control of each Placemark.

**Comment by ComBatVision** [comment]
Fixed in 469794a7b1b207af78f44ab9f8ee3ce0f1dc90aa
