### ISSUE TITLE
Fix limitation of 3D Path length

### ISSUE THREAD

**Issue by ComBatVision** [WorldWindEarth/WorldWindKotlin#33]
For some reasons 3D path does not visualize more than about 3000 points.
But  the same path switched to surface texture mode displays full length.

**Comment by AlexanderStrashnenko** [comment]
https://community.arm.com/support-forums/f/graphics-gaming-and-vr-forum/55087/opengl-renders-only-a-part-of-bufferdata

**Comment by ComBatVision** [comment]
Fixed in 5596d432

The main reason the Path and Polygon have limited number of points to be drawn is
that vertexBuffer indices are UNSIGNED_SHORT type and thus
unique index values are limited due to "Max Short" value.

Add IntBufferObject, make Path use it as drawState.elementBuffer.
Change interiorElements, outlineElements and verticalElements type to
Int.
