### ISSUE TITLE
Geopackage Tile Matrix Set defined in meters for EPSG:3857 is not supported

### ISSUE THREAD

**Issue by CodeK1988** [WorldWindEarth/WorldWindKotlin#50]
hi mate,   load gpkg file  get error message 
"java.lang.IllegalArgumentException: Angle.init: NaN is not supported!"
"GpkgLayerFactory.createLayer: Unsupported GeoPackage contents"

`
val geoPackageFile = TutorialUtil.unpackAsset(requireContext(), "rivers.gpkg")

val layer = GpkgLayerFactory.createLayer(geoPackageFile.path)
`

Do you have more examples of loading gpkg files? For example, global vector map .gpkg file.   I tried several gpkg files but they all failed to load.

**Comment by ComBatVision** [comment]
Vector GPKG is not supported. Only raster tiles in EPSG 3857 or 4326.

**Comment by CodeK1988** [comment]
mate , now get error "(1) no such table: gpkg_2d_gridded_coverage_ancillary"

**Comment by ComBatVision** [comment]
It is because there is no elevation data in your example file

чт, 23 лист. 2023, 04:32 користувач Code K ***@***.***> пише:

**Comment by CodeK1988** [comment]
hi mate, do you have an example gpkg map file with elevation? I'd like to try it. I tried QGIS to convert my map file mbtiles format to gpkg, but it didn't load successfully. Best wishes and thanks for your reply. @ComBatVision

**Comment by ComBatVision** [comment]
Here is an example of elevations file.
But be aware that curently WWK does not support PNG16 or TIFF32 compression of evevation tils.
It stores tiles data in BIL16 and BIL32 formats which is not by standard.
One of our issues in the list is to add support of PNG and TIFF.
[elevation.zip](https://github.com/WorldWindEarth/WorldWindKotlin/files/13457843/elevation.zip)

**Comment by CodeK1988** [comment]
`
GeoPackage layer creation failed
   java.lang.IllegalArgumentException: GpkgLayerFactory.createLayer: Unsupported GeoPackage contents
at earth.worldwind.ogc.GpkgLayerFactory.createLayer(GpkgLayerFactory.kt:20)
at earth.worldwind.ogc.GpkgLayerFactory$createLayer$1.invokeSuspend(Unknown Source:15)
`
bro, this file gets the same error. @ComBatVision

**Comment by ComBatVision** [comment]
Have you selected layer name with content type "tiles" as a second paramater in createLayer?

**Comment by CodeK1988** [comment]
> Have you selected layer name with content type "tiles" as a second paramater in createLayer?

I'm a newbie, and I loaded the elevation.gpkg file get error.

**Comment by ComBatVision** [comment]
Elevation.gpkg contains elwvation data, but you use GpkgLayerFactory which is intended to work with map layers "tiles" content only.

To add elevation you need to use GpkgElevationCoverage.

**Comment by ComBatVision** [comment]
Fixed in 16edebfe

**Comment by CodeK1988** [comment]
hi mate, i get error message. I tried to convert tif format to gpkg format by QGIS desktop.
`
(1) no such table: gpkg_extensions
(1) no such table: gpkg_2d_gridded_coverage_ancillary
(1) no such table: gpkg_web_service

GpkgLayerFactory createGeoPackageLayer levelSet：3857
GeoPackage layer creation succeeded

Error inserting UNIQUE constraint failed: gpkg_web_service.table_name (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 2:No such file or directory)
Error inserting UNIQUE constraint failed: gpkg_web_service.table_name (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 2:No such file or directory)

`

**Comment by CodeK1988** [comment]
[BJ.zip](https://github.com/WorldWindEarth/WorldWindKotlin/files/13763571/BJ.zip)
my gpkg file. is this format not currently supported? Looking forward to replying.

**Comment by ComBatVision** [comment]
![Screenshot_20231225-140325_WorldWind Tutorials.jpg](https://github.com/WorldWindEarth/WorldWindKotlin/assets/12487306/6fc45219-2de1-447a-b647-388bea27c03e)

**Comment by ComBatVision** [comment]
Yes, you can use your own geopackage elevation through GpkgContentManager.getElevations()

**Comment by CodeK1988** [comment]
@ComBatVision i get error Unsupported GeoPackage content data_type: tiles.   "Unsupported GeoPackage content data_type: " + content.dataType. 
i Downloaded tif converted to gpkg. should i do something?

**Comment by ComBatVision** [comment]
It should be not a map tiles geopackage content type, but 2d-gridded-coverage.

Read about how heopackage should store elevation data.

**Comment by CodeK1988** [comment]
@ComBatVision hi mate, is there any elevation data that supports downloading?  geopackage format.  i tried,but all failed.     
Or is there a sample file? I want to see the effect.  thanks!

**Comment by ComBatVision** [comment]
Download an example file from tutorials application. It caches elevations from wms.worldwind.earth/elev server to geopackage.

**Comment by CodeK1988** [comment]
@ComBatVision hi mate, I can't find the "GpkgContentManager.getElevations()" method. Does it support me to directly use elevation data in tif or gpkg format? How to use?

<img width="1031" alt="1708312954397" src="https://github.com/WorldWindEarth/WorldWindKotlin/assets/13393518/f4fc4b70-1a83-4691-a725-260e3b3807c8">

**Comment by CodeK1988** [comment]
And would like to ask, if I have multiple gpkg different regions with different levels of files how do I load them? Is it just a for loop to traverse and add layers?

`
wwd.engine.layers.addLayer(layer)???
`

**Comment by ComBatVision** [comment]
You do not need to configure cache. You need to create GpkgContentManager instance and call getTikedElevationCoveragws or something like this (i need to see correct method nane). It will return the list of coverages and you need to call wwd.engine.globe.elevationModel.addAllCoverages(returnedList)

**Comment by ComBatVision** [comment]
Your aproach should be used when you configure new cache for the map or elevation.

**Comment by CodeK1988** [comment]
@ComBatVision hi bro, is that what you mean? Could you be more specific, pls?
<img width="788" alt="1708484385853" src="https://github.com/WorldWindEarth/WorldWindKotlin/assets/13393518/a259abf5-f669-4dc5-88ba-08468bf8b9c0">

just like this
https://github.com/CelestialMappingSystem/WorldWindJava/blob/9feb40d9676878b8b59b52ea78eae880895e77cb/src/gov/nasa/cms/features/MoonElevationModel.java#L24

**Comment by ComBatVision** [comment]
Yes. Your screenshot is correct.

**Comment by CodeK1988** [comment]
I know I am super annoying, but my screenshot doesn't work properly. Are there any more detailed code examples? thank you. @ComBatVision

**Comment by ComBatVision** [comment]
Convert or cast list of tiled elecation coverages to list of coverage interfaces or insert each coverage in the loop one by one using addCoverage.

**Comment by CodeK1988** [comment]
@ComBatVision It's my fault, I didn't read the returned results carefully. but whats 
But what is the parameter contentKeys? 
I think I'm one step closer, mate

**Comment by ComBatVision** [comment]
It is a filter bybtable name if you do not want all coverages to be created.

**Comment by CodeK1988** [comment]
[BJJ.zip](https://github.com/WorldWindEarth/WorldWindKotlin/files/14401862/BJJ.zip)

@ComBatVision Now I get some error logs
`
GeoPackage layer creation succeeded
(1) no such table: gpkg_web_service
GpkgContentManager.getElevationCoverages: Problems executing Android query: SELECT * FROM `gpkg_web_service` WHERE `table_name` = 'BJ' LIMIT 1
`
My code looks like this
`
val filePath = TutorialUtil.unpackAsset(requireContext(), "BJJ.gpkg")
        val gpkgContentManager = GpkgContentManager(filePath.absolutePath)
        wwd.mainScope.launch {
            val elevationCoverages = gpkgContentManager.getElevationCoverages(null)
            Logger.log(Logger.ERROR, "getElevationCoverages:$elevationCoverages")
            for (elevationCoverage in elevationCoverages) {
                wwd.engine.globe.elevationModel.addCoverage(elevationCoverage)
            }
        }
`
I just exported the elevation file in tif format to gpkg file format through QGIS.
What else do I need to do? Thanks Reply.

**Comment by ComBatVision** [comment]
It is an issue in the latest ORM based GeoPackage processing logic. We need to fix it.

**Comment by CodeK1988** [comment]
> It is an issue in the latest ORM based GeoPackage processing logic. We need to fix it.
@ComBatVision okay, Looking forward to your good news, buddy.

**Comment by ComBatVision** [comment]
@CodeK1988 Pleasem use the latest vrsion 1.4.11. We have fixed that crash.

**Comment by CodeK1988** [comment]
@ComBatVision Well done buddy, I loaded it successfully !!! I still need to ask some questions.
1.Do I need to add multiple elevation data sources of different map levels in the offline environment?
2.Are both offline elevation and online elevation supported? Can they be used together?
3.When I add multiple adjacent map data of different levels, will there be gaps?

Forgive me, my English is not very good, thank you for everything you have done for the project. 
Can I get your contact details? If I encounter any problems later, I still need to consult you. If some of the problems are more difficult, we can pay, although our budget is limited.
my e-mail address is pankun163@gmail.com.

**Comment by ComBatVision** [comment]
1. You may have one geopackage with different level of details or several sources with different level of details, but in second case order in the list is betters. More detailed data should go later than less detailed.
2. Yes. You can use configureCache method to attach offline geopackage cache to online source or add online and oflune sources as two different sources.
3.What gaps do you mean?

support (at) combat (dot) vision

**Comment by CodeK1988** [comment]
@ComBatVision thank you for your reply.  3 This means that if I only load the offline 3D map of some areas, other areas will appear uncoordinated and will have obvious white or black edges.   Or is there a map box? I only load the area within the specified latitude and longitude.
