### ISSUE TITLE
Add support for full offline and various offline file formats

### ISSUE THREAD

**Issue by CodeK1988** [WorldWindEarth/WorldWindKotlin#54]
hi mate, we want to achieve a completely offline 3D map. It would be great if you could support it.

**Comment by ComBatVision** [comment]
Task is not understandable. WorldWind already support any epsg 4326 or 3857 XYX, WMS and WMTS raster online map sources and any WCS elevation sources in bil16, bil32 and tiff formats, plus it support GeoPackage, but we have two opened issues about incorrect epsg 3857 and elevation saving into gpks file, which will be foxed this month.

What additionaly do you want?

**Comment by CodeK1988** [comment]
Can tif and dem be loaded normally after being converted to geopack format?

**Comment by ComBatVision** [comment]
We are working now on tiff and png16 support. Currently gpkg supports only bil16 and bil32 formats.

**Comment by CodeK1988** [comment]
Good looking forward to it, I have been stuck in the offline 3D map for a long time. I would like to load a map file in tif or mbtiles format as a 3D scene in a worldwind map. thanks bro!

**Comment by ComBatVision** [comment]
It will  be in milestone 1.4.0.
