### ISSUE TITLE
Add possibility to specify Label visibility threshold

### ISSUE THREAD

**Issue by ComBatVision** [WorldWindEarth/WorldWindKotlin#64]
Currently there is no possibility to hide text from distance.
We need to add possibility to specify Label visibility threshold

**Comment by ComBatVision** [comment]
Added Label.visibilityThreshold attribute.

**Comment by pionkhaipv** [comment]
How do you add this attribute? Can you show me? Thank you @ComBatVision

**Comment by ComBatVision** [comment]
Just set label.visibilityThreshold = some camera distance and text will disapear after this distance.
